### ISSUE TITLE
Non Secure app message when running it locally.

### ISSUE THREAD

**Issue by vatsilidis** [meta-quest/webxr-showcases#4]
While running both showcases in localhost the browser prompts me not to proceed because it is https instead of http.
Probably this is coming from the webpack devServer.server setting.

**Comment by felixtrz** [comment]
This is expected. The browser warning can be easily dismissed by clicking on "Advanced" and then "Proceed to localhost"

WebXR requires secure context, hence https instead of http, and you don't need to bother with a valid certificate when testing on localhost

<img width="1804" alt="Screenshot 2024-10-16 at 2 23 00 PM" src="https://github.com/user-attachments/assets/38a74cf2-35e9-4c6b-8085-b5153110021c">
